
# find correct python image
FROM baseImage

WORKDIR /
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0

# requirements.txt and installing dependancies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN npm install quagga

COPY . .
CMD ["flask", "run"]